blog/urls.py
#
from django.conf.urls import include, url
from.import views
#from django.conf import settings
#from django.conf.urls import patterns, include, url
#from django.contrib import admin

app_name = "blog"
urlpatterns = [
    url(r'^$', views.post_list),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name="post_detail"),
   # url(r'^show/(?P<ticket_id>[0-9]+)', "showticket", name="showticket"),
   # url(r'^mytickets/', views.dashboard, name="view_dashboard"),
]

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from django.shortcuts import render, get_object_or_404

# Create your views here.
def post_list(request):
 	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
 	return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request,pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})
    # Post.objects.get(pk=pk)

blog/templates/blog/base.html
 {% load staticfiles %}
 
    <html>
        <head>
         <!--   <title>Help Desk With Django</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <link rel="shortcut icon" href="images/helpdesk.png">
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css">
            <link rel="stylesheet" href="{% static 'css/sb-admin.css'%}" type="text/css">
            <link rel="stylesheet" href="{% static 'css/morris.css'%}" type="text/css">

            -->

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
        <meta name="author" content="Coderthemes">
        <link rel="shortcut icon" href="images/logo.png">
        <title>Help Desk With Django</title>
         <link href="{% static 'plugins/notifications/notification.css'%}" rel="stylesheet">
        <link href="{% static 'plugins/sweetalert/dist/sweetalert.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'plugins/datatables/jquery.dataTables.min.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'plugins/RWD-Table-Patterns/dist/css/rwd-table.min.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'%}" rel="stylesheet">
        <link href="{% static 'plugins/modal-effect/css/component.css'%}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/core.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/icons.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/components.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/pages.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/menu.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/responsive.css'%}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/custom.css'%}" rel="stylesheet" type="text/css">
       

           <!--  {% block head %}{% endblock %}
           <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
            <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="{% static 'css/blog.css' %}"-->

        </head>
       <body class="fixed-left">
        <!-- Begin page -->
        <div id="wrapper">
            <!-- Top Bar Start Header -->
    <div class="topbar">
    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center"><a  class="logo"><i class="md md-blur-on"></i> <span>Fisi</span></a></div>
    </div>
    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button class="button-menu-mobile open-left"><i class="fa fa-bars"></i></button> <span class="clearfix"></span></div>
                <!--                        <form class="navbar-form pull-left" role="search">
                                            <div class="form-group">
                                                <input type="text" class="form-control search-bar" placeholder="Type here for search...">
                                            </div>
                                            <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                                        </form>-->
                <ul class="nav navbar-nav navbar-right pull-right">
                     <li class="hidden-xs"><a href="#" id="btn-fullscreen" class="waves-effect"><i class="md md-crop-free"></i></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle profile" data-toggle="dropdown" aria-expanded="true"><i class="md md-account-circle"></i>
                          <span class="hidden-xs" >Carolina Cáceda</span>
                         </a>
                        <ul class="dropdown-menu">
<!--                                    <li><a href="javascript:void(0)"><i class="md md-face-unlock"></i> Profile</a></li>
                            <li><a href="javascript:void(0)"><i class="md md-settings"></i> Settings</a></li>
                            <li><a href="javascript:void(0)"><i class="md md-lock"></i> Lock screen</a></li>-->
                            <li><a href="/"><i class="md md-settings-power"></i> Cerrar Sesion</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
            <!-- Top Bar End -->
            <!-- ========== navar========== -->
         <div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">


        <!--- Divider -->
        <div id="sidebar-menu">
          
            <ul>
                <li><a href="/" class=""><i class="md md-hearing"></i><span>SISTEMA  DE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HELPDESK </span></a></li>
                  
                  <li class="has_sub"><a href="#" class=""><i class="md md-loyalty"></i><span>Tickets</span><span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li class=""><a href="/">Consultar Servicios</a></li>
                        <li class=""><a href="/">Registrar Tickets(BC)</a></li>
                        <li class=""><a href="/">Consultar Tickets(CE)</a></li>

                    </ul>
                </li>
                     <li class="has_sub"><a href="#" class=""><i class="md md-loyalty"></i><span>Tickets Técnico</span><span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li class=""><a href="/">Consultar Servicios</a></li>
                        <li class=""><a href="/">Consultar Tickets(AE)</a></li>
                    </ul>
                </li>
                </li>
                     <li class="has_sub"><a href="#" class=""><i class="md md-loyalty"></i><span>Tickets Admin</span><span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li class=""><a href="/">Consultar Base de Concimiento</a></li>
                        <li class=""><a href="/">Quejas y Reclamos</a></li>
                        <li class=""><a href="/">Reportes</a></li>
                    </ul>
                </li>
                   <li class="has_sub"><a href="#" class=""><i class="md md-chat"></i><span>Técnicos</span><span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li class=""><a href="/">Ver todos</a></li>
                        <li class=""><a href="/">Nuevo</a></li>
                        <li class=""><a href="/">Reportes</a></li>
                    </ul>
                </li>
                  
                    <li><a href="/" class="waves-effect waves-light "><i class="md  md-rotate-left"></i><span>Volver a Home</span></a></li>
                
            </ul>
           
                  
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
            <!-- Left Sidebar End -->
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">
                       {% block content %}  {% endblock %}

                    </div>
                    <!-- container -->  
                </div>
                <!-- footer -->
              <footer class="footer text-right">2017 © Helpdesk- Caro</footer>
                       
            </div>
            
        </div>
        <!-- END wrapper -->
        <script>
            var resizefunc = [];
        </script>
        <!-- jQuery  -->
         <script src="{% static 'js/modernizr.min.js'%}"></script>
        <script src="{% static 'js/jquery.min.js'%}"></script>
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
        <script src="{% static 'js/detect.js'%}"></script>
        <script src="{% static 'js/myjava.js'%}"></script>
        <script src="{% static 'js/fastclick.js'%}"></script>
        <script src="{% static 'js/jquery.slimscroll.js'%}"></script>
        <script src="{% static 'js/jquery.blockUI.js'%}"></script>
        <script src="{% static 'js/waves.js'%}"></script>
        <script src="{% static 'js/wow.min.js'%}"></script>
        <script src="{% static 'js/jquery.nicescroll.js'%}"></script>
        <script src="{% static 'js/jquery.scrollTo.min.js'%}"></script>
        <script src="{% static 'js/jquery.app.js'%}"></script>
        <!-- moment js  -->
        <script src="{% static 'plugins/moment/moment.js'%}"></script>
        <!-- counters  -->
        <script src="{% static 'plugins/waypoints/lib/jquery.waypoints.js'%}"></script>
        <script src="{% static 'plugins/counterup/jquery.counterup.min.js'%}"></script>
        <!-- sweet alert  -->
        <script src="{% static 'plugins/sweetalert/dist/sweetalert.min.js'%}"></script>
        <script src="{% static 'pages/jquery.sweet-alert.init.js'%}"></script>
        
        <!-- flot Chart -->
        <script src="{% static 'plugins/flot-chart/jquery.flot.js'%}"></script>
        <script src="{% static 'plugins/flot-chart/jquery.flot.time.js'%}"></script>
        <script src="{% static 'plugins/flot-chart/jquery.flot.tooltip.min.js'%}"></script>
        <script src="{% static 'plugins/flot-chart/jquery.flot.resize.js'%}"></script>
        <script src="{% static 'plugins/flot-chart/jquery.flot.pie.js'%}"></script>
        <script src="{% static 'plugins/flot-chart/jquery.flot.selection.js'%}"></script>
        <script src="{% static 'plugins/flot-chart/jquery.flot.stack.js'%}"></script>
        <script src="{% static 'plugins/flot-chart/jquery.flot.crosshair.js'%}"></script>
        <script src="{% static 'plugins/datatables/jquery.dataTables.min.js'%}"></script>
        <script src="{% static 'plugins/datatables/dataTables.bootstrap.js'%}"></script>
        <script src="{% static 'plugins/RWD-Table-Patterns/dist/js/rwd-table.min.js'%}"></script>
        <!-- todos app  -->
        <script src="{% static 'pages/jquery.todo.js'%}"></script>
        <!-- chat app  -->
        <script src="{% static 'pages/jquery.chat.js'%}"></script>
        <!-- dashboard  -->
        <script src="{% static 'pages/jquery.dashboard.js'%}"></script>
        <!--form validation-->
        <script type="text/javascript" src="{% static 'plugins/jquery-validation/dist/jquery.validate.min.js'%}"></script>
        <!--form validation init-->
        <script src="{% static 'pages/form-validation-init.js"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'%}"></script>
        <!-- Modal-Effect -->
        <script src="{% static 'plugins/modal-effect/js/classie.js'%}"></script>
        <script src="{% static 'plugins/modal-effect/js/modalEffects.js'%}"></script>
        <script src="{% static 'plugins/notifyjs/dist/notify.min.js'%}"></script>
        <script src="{% static 'plugins/notifications/notify-metro.js'%}"></script>
        <script src="{% static 'plugins/notifications/notifications.js'%}"></script>
        <script src="{% static 'js/custom.js'%}"></script>
    </body>
    </html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="post">
 {% if post.published_date %}
<div class="date">
 {{ post.published_date }}
  </div>
 {% endif %}
<h1>{{ post.title }}</h1>
<p>{{ post.text|linebreaksbr }}</p>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}



<div class="col-lg-12">
   <div class="panel panel-border panel-primary " > <center>

      <div class="panel-heading">
         <h1 class="text-primary"><strong><FONT SIZE=4>Tickets Registrados Último Mes</FONT></strong></h1>
    <h1 class="text-muted"><strong><FONT SIZE=3>Abril-2017</FONT></strong></h1>
</div>
      <div class="panel-body">
                  <table id="example" class="display table table-small-font table-bordered table-striped  pull-rigth">
                     <thead>
                        <tr>
                           <th >Fecha</th>
                           <th >Solicitante</th>
                           <th>Asunto</th>
                        </tr>
                     </thead>
                     <tfoot >
                        <tr>
                          
                           <td  >Fecha</td>
                           <td  >Solicitante</td>
                           <td  >Asunto</td>
                        </tr>
                     </tfoot>
                     <tbody>


{% for post in posts %}
 <tr>

   <td> {{ post.published_date }}</td>
 <!-- <h1><a href="/">{{ post.title }}</a></h1> -->
   <td><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></td>
   <td>{{ post.text|linebreaksbr }}</td>
  
    </tr>
{% endfor %}
 </tbody>  
                    
                  </table>
                  </div> </center>
   </div>
  </div>

{% endblock %}          